# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_Helmholtz.ui'
#
# Created: Fri Aug 18 12:25:15 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Helmholtz(object):
    def setupUi(self, Helmholtz):
        Helmholtz.setObjectName(_fromUtf8("Helmholtz"))
        Helmholtz.resize(864, 360)
        Helmholtz.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.centralwidget = QtGui.QWidget(Helmholtz)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(-1, 0, 871, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(510, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_42 = QtGui.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(50, 0, 301, 291))
        self.label_42.setText(_fromUtf8(""))
        self.label_42.setPixmap(QtGui.QPixmap(_fromUtf8("Imagens/Helmholtz2.jpg")))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.layoutWidget = QtGui.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(440, 81, 305, 111))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(67)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cb_PortaDisplay = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_PortaDisplay.setFont(font)
        self.cb_PortaDisplay.setObjectName(_fromUtf8("cb_PortaDisplay"))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cb_PortaDisplay, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.cb_PortaDriver = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_PortaDriver.setFont(font)
        self.cb_PortaDriver.setObjectName(_fromUtf8("cb_PortaDriver"))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cb_PortaDriver, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.le_EndIntegrador = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_EndIntegrador.setFont(font)
        self.le_EndIntegrador.setObjectName(_fromUtf8("le_EndIntegrador"))
        self.gridLayout.addWidget(self.le_EndIntegrador, 2, 1, 1, 1)
        self.pb_ConectarDispositivos = QtGui.QPushButton(self.tab_3)
        self.pb_ConectarDispositivos.setGeometry(QtCore.QRect(450, 207, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_ConectarDispositivos.setFont(font)
        self.pb_ConectarDispositivos.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ConectarDispositivos.setIcon(icon)
        self.pb_ConectarDispositivos.setIconSize(QtCore.QSize(35, 35))
        self.pb_ConectarDispositivos.setObjectName(_fromUtf8("pb_ConectarDispositivos"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.widget_3 = matplotlibWidget_2(self.tab_8)
        self.widget_3.setGeometry(QtCore.QRect(349, 0, 511, 301))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.pb_temperatura = QtGui.QPushButton(self.tab_8)
        self.pb_temperatura.setGeometry(QtCore.QRect(110, 10, 221, 38))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_temperatura.setFont(font)
        self.pb_temperatura.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pb_temperatura.setIcon(icon)
        self.pb_temperatura.setIconSize(QtCore.QSize(30, 30))
        self.pb_temperatura.setObjectName(_fromUtf8("pb_temperatura"))
        self.cb_PortaMultimetro = QtGui.QComboBox(self.tab_8)
        self.cb_PortaMultimetro.setGeometry(QtCore.QRect(10, 10, 91, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_PortaMultimetro.setFont(font)
        self.cb_PortaMultimetro.setObjectName(_fromUtf8("cb_PortaMultimetro"))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.cb_PortaMultimetro.addItem(_fromUtf8(""))
        self.line = QtGui.QFrame(self.tab_8)
        self.line.setGeometry(QtCore.QRect(7, 50, 331, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab_8)
        self.line_2.setGeometry(QtCore.QRect(10, 125, 331, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.widget = QtGui.QWidget(self.tab_8)
        self.widget.setGeometry(QtCore.QRect(20, 170, 311, 22))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_47 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_6.addWidget(self.label_47)
        self.le_Medidas = QtGui.QLineEdit(self.widget)
        self.le_Medidas.setAlignment(QtCore.Qt.AlignCenter)
        self.le_Medidas.setObjectName(_fromUtf8("le_Medidas"))
        self.horizontalLayout_6.addWidget(self.le_Medidas)
        self.label_49 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_6.addWidget(self.label_49)
        self.label_atual = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_atual.setFont(font)
        self.label_atual.setAlignment(QtCore.Qt.AlignCenter)
        self.label_atual.setObjectName(_fromUtf8("label_atual"))
        self.horizontalLayout_6.addWidget(self.label_atual)
        self.le_error = QtGui.QLineEdit(self.tab_8)
        self.le_error.setGeometry(QtCore.QRect(10, 280, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.le_error.setFont(font)
        self.le_error.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.le_error.setStyleSheet(_fromUtf8("background-color: rgb(227, 227, 227);\n"
"border-color: rgb(227, 227, 227);"))
        self.le_error.setAlignment(QtCore.Qt.AlignCenter)
        self.le_error.setReadOnly(True)
        self.le_error.setObjectName(_fromUtf8("le_error"))
        self.widget1 = QtGui.QWidget(self.tab_8)
        self.widget1.setGeometry(QtCore.QRect(10, 230, 321, 41))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pb_IniciaColeta = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_IniciaColeta.setFont(font)
        self.pb_IniciaColeta.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621501_Check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_IniciaColeta.setIcon(icon1)
        self.pb_IniciaColeta.setIconSize(QtCore.QSize(20, 20))
        self.pb_IniciaColeta.setObjectName(_fromUtf8("pb_IniciaColeta"))
        self.horizontalLayout_8.addWidget(self.pb_IniciaColeta)
        self.pb_PararColeta = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_PararColeta.setFont(font)
        self.pb_PararColeta.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621507_Delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_PararColeta.setIcon(icon2)
        self.pb_PararColeta.setIconSize(QtCore.QSize(20, 20))
        self.pb_PararColeta.setObjectName(_fromUtf8("pb_PararColeta"))
        self.horizontalLayout_8.addWidget(self.pb_PararColeta)
        self.widget2 = QtGui.QWidget(self.tab_8)
        self.widget2.setGeometry(QtCore.QRect(20, 140, 311, 21))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cb_Salvar = QtGui.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_Salvar.setFont(font)
        self.cb_Salvar.setObjectName(_fromUtf8("cb_Salvar"))
        self.horizontalLayout_5.addWidget(self.cb_Salvar)
        self.cb_ArmazenaTempo = QtGui.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_ArmazenaTempo.setFont(font)
        self.cb_ArmazenaTempo.setObjectName(_fromUtf8("cb_ArmazenaTempo"))
        self.horizontalLayout_5.addWidget(self.cb_ArmazenaTempo)
        self.widget3 = QtGui.QWidget(self.tab_8)
        self.widget3.setGeometry(QtCore.QRect(20, 200, 311, 22))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_48 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_7.addWidget(self.label_48)
        self.le_Intervalo = QtGui.QLineEdit(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.le_Intervalo.setFont(font)
        self.le_Intervalo.setAlignment(QtCore.Qt.AlignCenter)
        self.le_Intervalo.setObjectName(_fromUtf8("le_Intervalo"))
        self.horizontalLayout_7.addWidget(self.le_Intervalo)
        self.label_50 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_7.addWidget(self.label_50)
        self.widget4 = QtGui.QWidget(self.tab_8)
        self.widget4.setGeometry(QtCore.QRect(20, 70, 311, 24))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_43 = QtGui.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_3.addWidget(self.label_43)
        self.le_espera = QtGui.QLineEdit(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_espera.setFont(font)
        self.le_espera.setEchoMode(QtGui.QLineEdit.Normal)
        self.le_espera.setAlignment(QtCore.Qt.AlignCenter)
        self.le_espera.setObjectName(_fromUtf8("le_espera"))
        self.horizontalLayout_3.addWidget(self.le_espera)
        self.widget5 = QtGui.QWidget(self.tab_8)
        self.widget5.setGeometry(QtCore.QRect(20, 100, 311, 24))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget5)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_46 = QtGui.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_4.addWidget(self.label_46)
        self.le_resistencia = QtGui.QLineEdit(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_resistencia.setFont(font)
        self.le_resistencia.setAlignment(QtCore.Qt.AlignCenter)
        self.le_resistencia.setObjectName(_fromUtf8("le_resistencia"))
        self.horizontalLayout_4.addWidget(self.le_resistencia)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.pb_SalvarParametros = QtGui.QPushButton(self.tab_5)
        self.pb_SalvarParametros.setGeometry(QtCore.QRect(250, 230, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_SalvarParametros.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621493_Burn Disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_SalvarParametros.setIcon(icon3)
        self.pb_SalvarParametros.setIconSize(QtCore.QSize(35, 35))
        self.pb_SalvarParametros.setObjectName(_fromUtf8("pb_SalvarParametros"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(90, 30, 681, 171))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.le_EndDriver = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_EndDriver.setObjectName(_fromUtf8("le_EndDriver"))
        self.gridLayout_2.addWidget(self.le_EndDriver, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.le_VelMedida = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_VelMedida.setText(_fromUtf8(""))
        self.le_VelMedida.setObjectName(_fromUtf8("le_VelMedida"))
        self.gridLayout_2.addWidget(self.le_VelMedida, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.le_AceMedida = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_AceMedida.setObjectName(_fromUtf8("le_AceMedida"))
        self.gridLayout_2.addWidget(self.le_AceMedida, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.le_NVoltas = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_NVoltas.setObjectName(_fromUtf8("le_NVoltas"))
        self.gridLayout_2.addWidget(self.le_NVoltas, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.le_PulsosEncoder = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_PulsosEncoder.setObjectName(_fromUtf8("le_PulsosEncoder"))
        self.gridLayout_3.addWidget(self.le_PulsosEncoder, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.le_PassosMotor = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_PassosMotor.setObjectName(_fromUtf8("le_PassosMotor"))
        self.gridLayout_3.addWidget(self.le_PassosMotor, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.cb_PontosIntegracao = QtGui.QComboBox(self.layoutWidget_2)
        self.cb_PontosIntegracao.setObjectName(_fromUtf8("cb_PontosIntegracao"))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cb_PontosIntegracao, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.le_TriggerAlinhamento = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_TriggerAlinhamento.setObjectName(_fromUtf8("le_TriggerAlinhamento"))
        self.gridLayout_3.addWidget(self.le_TriggerAlinhamento, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(110, 32, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 80, 360, 180))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setSpacing(14)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setContentsMargins(10, 1, 0, -1)
        self.gridLayout_4.setHorizontalSpacing(45)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_15 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.le_nEspiras = QtGui.QLineEdit(self.layoutWidget_3)
        self.le_nEspiras.setObjectName(_fromUtf8("le_nEspiras"))
        self.gridLayout_4.addWidget(self.le_nEspiras, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.le_Raio1 = QtGui.QLineEdit(self.layoutWidget_3)
        self.le_Raio1.setObjectName(_fromUtf8("le_Raio1"))
        self.gridLayout_4.addWidget(self.le_Raio1, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.le_Raio2 = QtGui.QLineEdit(self.layoutWidget_3)
        self.le_Raio2.setObjectName(_fromUtf8("le_Raio2"))
        self.gridLayout_4.addWidget(self.le_Raio2, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 3, 0, 1, 1)
        self.le_DistCentro = QtGui.QLineEdit(self.layoutWidget_3)
        self.le_DistCentro.setObjectName(_fromUtf8("le_DistCentro"))
        self.gridLayout_4.addWidget(self.le_DistCentro, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.pb_SalvarBobina = QtGui.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_SalvarBobina.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621516_Burn Disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_SalvarBobina.setIcon(icon4)
        self.pb_SalvarBobina.setIconSize(QtCore.QSize(35, 35))
        self.pb_SalvarBobina.setObjectName(_fromUtf8("pb_SalvarBobina"))
        self.verticalLayout_3.addWidget(self.pb_SalvarBobina)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(500, 10, 301, 291))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8("Imagens/HelmholtzConfig.png")))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(80, 30, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(520, 30, 231, 221))
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setPixmap(QtGui.QPixmap(_fromUtf8("Imagens/MotorPasso4.png")))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.layoutWidget_4 = QtGui.QWidget(self.tab_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(70, 80, 301, 141))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_20 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_12.addWidget(self.label_20, 0, 0, 1, 1)
        self.le_VelMotor = QtGui.QLineEdit(self.layoutWidget_4)
        self.le_VelMotor.setObjectName(_fromUtf8("le_VelMotor"))
        self.gridLayout_12.addWidget(self.le_VelMotor, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_12.addWidget(self.label_21, 1, 0, 1, 1)
        self.le_AceMotor = QtGui.QLineEdit(self.layoutWidget_4)
        self.le_AceMotor.setObjectName(_fromUtf8("le_AceMotor"))
        self.gridLayout_12.addWidget(self.le_AceMotor, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_12.addWidget(self.label_22, 2, 0, 1, 1)
        self.cb_HabilitaEncoder = QtGui.QCheckBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_HabilitaEncoder.setFont(font)
        self.cb_HabilitaEncoder.setObjectName(_fromUtf8("cb_HabilitaEncoder"))
        self.gridLayout_12.addWidget(self.cb_HabilitaEncoder, 3, 0, 1, 1)
        self.le_NVoltasMotor = QtGui.QLineEdit(self.layoutWidget_4)
        self.le_NVoltasMotor.setObjectName(_fromUtf8("le_NVoltasMotor"))
        self.gridLayout_12.addWidget(self.le_NVoltasMotor, 2, 1, 1, 1)
        self.le_LeituraEncoder = QtGui.QLineEdit(self.layoutWidget_4)
        self.le_LeituraEncoder.setReadOnly(True)
        self.le_LeituraEncoder.setObjectName(_fromUtf8("le_LeituraEncoder"))
        self.gridLayout_12.addWidget(self.le_LeituraEncoder, 3, 1, 1, 1)
        self.pb_MoverMotor = QtGui.QPushButton(self.tab_4)
        self.pb_MoverMotor.setGeometry(QtCore.QRect(70, 234, 145, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_MoverMotor.setFont(font)
        self.pb_MoverMotor.setIcon(icon1)
        self.pb_MoverMotor.setObjectName(_fromUtf8("pb_MoverMotor"))
        self.pb_PararMotor = QtGui.QPushButton(self.tab_4)
        self.pb_PararMotor.setEnabled(False)
        self.pb_PararMotor.setGeometry(QtCore.QRect(230, 234, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_PararMotor.setFont(font)
        self.pb_PararMotor.setIcon(icon2)
        self.pb_PararMotor.setObjectName(_fromUtf8("pb_PararMotor"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_26 = QtGui.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(60, 20, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.pb_ZerarOffsets = QtGui.QPushButton(self.tab)
        self.pb_ZerarOffsets.setGeometry(QtCore.QRect(520, 260, 161, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_ZerarOffsets.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/botao_limpar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ZerarOffsets.setIcon(icon5)
        self.pb_ZerarOffsets.setIconSize(QtCore.QSize(30, 30))
        self.pb_ZerarOffsets.setObjectName(_fromUtf8("pb_ZerarOffsets"))
        self.tw_GanhosOffsets = QtGui.QTableWidget(self.tab)
        self.tw_GanhosOffsets.setGeometry(QtCore.QRect(470, 14, 260, 245))
        self.tw_GanhosOffsets.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tw_GanhosOffsets.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tw_GanhosOffsets.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tw_GanhosOffsets.setSelectionBehavior(QtGui.QAbstractItemView.SelectColumns)
        self.tw_GanhosOffsets.setRowCount(7)
        self.tw_GanhosOffsets.setObjectName(_fromUtf8("tw_GanhosOffsets"))
        self.tw_GanhosOffsets.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        self.tw_GanhosOffsets.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tw_GanhosOffsets.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tw_GanhosOffsets.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(6, 1, item)
        self.tw_GanhosOffsets.horizontalHeader().setStretchLastSection(True)
        self.tw_GanhosOffsets.verticalHeader().setVisible(False)
        self.layoutWidget_5 = QtGui.QWidget(self.tab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(74, 63, 271, 151))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setVerticalSpacing(24)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_24 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_6.addWidget(self.label_24, 0, 0, 1, 1)
        self.le_NVoltasOffset = QtGui.QLineEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_NVoltasOffset.setFont(font)
        self.le_NVoltasOffset.setObjectName(_fromUtf8("le_NVoltasOffset"))
        self.gridLayout_6.addWidget(self.le_NVoltasOffset, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_6.addWidget(self.label_25, 1, 0, 1, 1)
        self.cb_GanhoOffset = QtGui.QComboBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_GanhoOffset.setFont(font)
        self.cb_GanhoOffset.setObjectName(_fromUtf8("cb_GanhoOffset"))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cb_GanhoOffset, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.pb_AjusteOffset = QtGui.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_AjusteOffset.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/FerramentaAjuste.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_AjusteOffset.setIcon(icon6)
        self.pb_AjusteOffset.setIconSize(QtCore.QSize(50, 50))
        self.pb_AjusteOffset.setObjectName(_fromUtf8("pb_AjusteOffset"))
        self.verticalLayout_4.addWidget(self.pb_AjusteOffset)
        self.pb_PararMedOffset = QtGui.QPushButton(self.tab)
        self.pb_PararMedOffset.setEnabled(False)
        self.pb_PararMedOffset.setGeometry(QtCore.QRect(211, 235, 156, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_PararMedOffset.setFont(font)
        self.pb_PararMedOffset.setIcon(icon2)
        self.pb_PararMedOffset.setObjectName(_fromUtf8("pb_PararMedOffset"))
        self.pb_IniciarMedOffset = QtGui.QPushButton(self.tab)
        self.pb_IniciarMedOffset.setGeometry(QtCore.QRect(48, 235, 157, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_IniciarMedOffset.setFont(font)
        self.pb_IniciarMedOffset.setIcon(icon1)
        self.pb_IniciarMedOffset.setObjectName(_fromUtf8("pb_IniciarMedOffset"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gb_MedirComponentes = QtGui.QGroupBox(self.tab_6)
        self.gb_MedirComponentes.setGeometry(QtCore.QRect(30, 10, 361, 281))
        self.gb_MedirComponentes.setTitle(_fromUtf8(""))
        self.gb_MedirComponentes.setObjectName(_fromUtf8("gb_MedirComponentes"))
        self.pb_Medicao = QtGui.QProgressBar(self.gb_MedirComponentes)
        self.pb_Medicao.setGeometry(QtCore.QRect(10, 245, 341, 23))
        self.pb_Medicao.setProperty("value", 50)
        self.pb_Medicao.setAlignment(QtCore.Qt.AlignCenter)
        self.pb_Medicao.setTextVisible(True)
        self.pb_Medicao.setOrientation(QtCore.Qt.Horizontal)
        self.pb_Medicao.setInvertedAppearance(False)
        self.pb_Medicao.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.pb_Medicao.setObjectName(_fromUtf8("pb_Medicao"))
        self.layoutWidget_6 = QtGui.QWidget(self.gb_MedirComponentes)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 13, 341, 101))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_28 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_7.addWidget(self.label_28, 1, 0, 1, 1)
        self.rb_DimensaoManual = QtGui.QRadioButton(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_DimensaoManual.setFont(font)
        self.rb_DimensaoManual.setCheckable(True)
        self.rb_DimensaoManual.setChecked(False)
        self.rb_DimensaoManual.setObjectName(_fromUtf8("rb_DimensaoManual"))
        self.gridLayout_7.addWidget(self.rb_DimensaoManual, 1, 1, 1, 1)
        self.rb_DimensaoAuto = QtGui.QRadioButton(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_DimensaoAuto.setFont(font)
        self.rb_DimensaoAuto.setObjectName(_fromUtf8("rb_DimensaoAuto"))
        self.gridLayout_7.addWidget(self.rb_DimensaoAuto, 1, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_7.addWidget(self.label_27, 2, 0, 1, 1)
        self.le_VolumeBloco = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco.setFont(font)
        self.le_VolumeBloco.setReadOnly(True)
        self.le_VolumeBloco.setObjectName(_fromUtf8("le_VolumeBloco"))
        self.gridLayout_7.addWidget(self.le_VolumeBloco, 2, 1, 1, 2)
        self.label_44 = QtGui.QLabel(self.layoutWidget_6)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_7.addWidget(self.label_44, 2, 3, 1, 1)
        self.cb_SubtrairVolume = QtGui.QCheckBox(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_SubtrairVolume.setFont(font)
        self.cb_SubtrairVolume.setObjectName(_fromUtf8("cb_SubtrairVolume"))
        self.gridLayout_7.addWidget(self.cb_SubtrairVolume, 3, 0, 1, 1)
        self.le_VolumeSubtracao = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeSubtracao.setFont(font)
        self.le_VolumeSubtracao.setReadOnly(True)
        self.le_VolumeSubtracao.setObjectName(_fromUtf8("le_VolumeSubtracao"))
        self.gridLayout_7.addWidget(self.le_VolumeSubtracao, 3, 1, 1, 2)
        self.label_45 = QtGui.QLabel(self.layoutWidget_6)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_7.addWidget(self.label_45, 3, 3, 1, 1)
        self.layoutWidget_7 = QtGui.QWidget(self.gb_MedirComponentes)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 129, 341, 111))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_7)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cb_CompPriMz = QtGui.QCheckBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_CompPriMz.setFont(font)
        self.cb_CompPriMz.setObjectName(_fromUtf8("cb_CompPriMz"))
        self.gridLayout_8.addWidget(self.cb_CompPriMz, 0, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_8.addWidget(self.label_29, 0, 2, 1, 1)
        self.cb_GanhoOffset_Mz = QtGui.QComboBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_GanhoOffset_Mz.setFont(font)
        self.cb_GanhoOffset_Mz.setObjectName(_fromUtf8("cb_GanhoOffset_Mz"))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cb_GanhoOffset_Mz, 0, 3, 1, 1)
        self.cb_CompSecMx = QtGui.QCheckBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_CompSecMx.setFont(font)
        self.cb_CompSecMx.setObjectName(_fromUtf8("cb_CompSecMx"))
        self.gridLayout_8.addWidget(self.cb_CompSecMx, 1, 0, 1, 1)
        self.cb_CompSecMy = QtGui.QCheckBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_CompSecMy.setFont(font)
        self.cb_CompSecMy.setObjectName(_fromUtf8("cb_CompSecMy"))
        self.gridLayout_8.addWidget(self.cb_CompSecMy, 2, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_8.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_8.addWidget(self.label_31, 2, 2, 1, 1)
        self.cb_GanhoOffset_Mx = QtGui.QComboBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_GanhoOffset_Mx.setFont(font)
        self.cb_GanhoOffset_Mx.setObjectName(_fromUtf8("cb_GanhoOffset_Mx"))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cb_GanhoOffset_Mx, 1, 3, 1, 1)
        self.cb_GanhoOffset_My = QtGui.QComboBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_GanhoOffset_My.setFont(font)
        self.cb_GanhoOffset_My.setObjectName(_fromUtf8("cb_GanhoOffset_My"))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cb_GanhoOffset_My, 2, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_8.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_8.addWidget(self.label_33, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_8.addWidget(self.label_34, 2, 1, 1, 1)
        self.pb_IniciarMedicao = QtGui.QPushButton(self.tab_6)
        self.pb_IniciarMedicao.setGeometry(QtCore.QRect(470, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_IniciarMedicao.setFont(font)
        self.pb_IniciarMedicao.setIcon(icon1)
        self.pb_IniciarMedicao.setObjectName(_fromUtf8("pb_IniciarMedicao"))
        self.pb_PararMedicao = QtGui.QPushButton(self.tab_6)
        self.pb_PararMedicao.setEnabled(False)
        self.pb_PararMedicao.setGeometry(QtCore.QRect(650, 200, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_PararMedicao.setFont(font)
        self.pb_PararMedicao.setIcon(icon2)
        self.pb_PararMedicao.setObjectName(_fromUtf8("pb_PararMedicao"))
        self.cb_SalvarDadosGerais = QtGui.QCheckBox(self.tab_6)
        self.cb_SalvarDadosGerais.setGeometry(QtCore.QRect(450, 260, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_SalvarDadosGerais.setFont(font)
        self.cb_SalvarDadosGerais.setObjectName(_fromUtf8("cb_SalvarDadosGerais"))
        self.label_41 = QtGui.QLabel(self.tab_6)
        self.label_41.setGeometry(QtCore.QRect(510, 20, 221, 191))
        self.label_41.setText(_fromUtf8(""))
        self.label_41.setPixmap(QtGui.QPixmap(_fromUtf8("Imagens/Helmholtz_vs2.jpg")))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_2.setGeometry(QtCore.QRect(0, -1, 851, 71))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_9.addWidget(self.label_35, 0, 0, 1, 1)
        self.le_VolumeBloco_3 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_3.setFont(font)
        self.le_VolumeBloco_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.le_VolumeBloco_3.setText(_fromUtf8(""))
        self.le_VolumeBloco_3.setReadOnly(True)
        self.le_VolumeBloco_3.setObjectName(_fromUtf8("le_VolumeBloco_3"))
        self.gridLayout_9.addWidget(self.le_VolumeBloco_3, 0, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_9.addWidget(self.label_36, 1, 0, 1, 1)
        self.le_VolumeBloco_4 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_4.setFont(font)
        self.le_VolumeBloco_4.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.le_VolumeBloco_4.setText(_fromUtf8(""))
        self.le_VolumeBloco_4.setReadOnly(True)
        self.le_VolumeBloco_4.setObjectName(_fromUtf8("le_VolumeBloco_4"))
        self.gridLayout_9.addWidget(self.le_VolumeBloco_4, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_10.addWidget(self.label_37, 0, 0, 1, 1)
        self.le_VolumeBloco_5 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_5.setFont(font)
        self.le_VolumeBloco_5.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.le_VolumeBloco_5.setText(_fromUtf8(""))
        self.le_VolumeBloco_5.setReadOnly(True)
        self.le_VolumeBloco_5.setObjectName(_fromUtf8("le_VolumeBloco_5"))
        self.gridLayout_10.addWidget(self.le_VolumeBloco_5, 0, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_10.addWidget(self.label_38, 1, 0, 1, 1)
        self.le_VolumeBloco_6 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_6.setFont(font)
        self.le_VolumeBloco_6.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.le_VolumeBloco_6.setText(_fromUtf8(""))
        self.le_VolumeBloco_6.setReadOnly(True)
        self.le_VolumeBloco_6.setObjectName(_fromUtf8("le_VolumeBloco_6"))
        self.gridLayout_10.addWidget(self.le_VolumeBloco_6, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_11.addWidget(self.label_39, 0, 0, 1, 1)
        self.le_VolumeBloco_7 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_7.setFont(font)
        self.le_VolumeBloco_7.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.le_VolumeBloco_7.setText(_fromUtf8(""))
        self.le_VolumeBloco_7.setReadOnly(True)
        self.le_VolumeBloco_7.setObjectName(_fromUtf8("le_VolumeBloco_7"))
        self.gridLayout_11.addWidget(self.le_VolumeBloco_7, 0, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_11.addWidget(self.label_40, 1, 0, 1, 1)
        self.le_VolumeBloco_8 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_8.setFont(font)
        self.le_VolumeBloco_8.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.le_VolumeBloco_8.setText(_fromUtf8(""))
        self.le_VolumeBloco_8.setReadOnly(True)
        self.le_VolumeBloco_8.setObjectName(_fromUtf8("le_VolumeBloco_8"))
        self.gridLayout_11.addWidget(self.le_VolumeBloco_8, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_11, 0, 2, 1, 1)
        self.widget6 = matplotlibWidget(self.tab_7)
        self.widget6.setGeometry(QtCore.QRect(0, 65, 430, 241))
        self.widget6.setObjectName(_fromUtf8("widget6"))
        self.widget_2 = matplotlibWidget_2(self.tab_7)
        self.widget_2.setGeometry(QtCore.QRect(432, 65, 430, 241))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        Helmholtz.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Helmholtz)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Helmholtz.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Helmholtz)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Helmholtz.setStatusBar(self.statusbar)

        self.retranslateUi(Helmholtz)
        self.tabWidget.setCurrentIndex(0)
        self.cb_PortaDisplay.setCurrentIndex(3)
        self.cb_PortaDriver.setCurrentIndex(4)
        self.cb_PortaMultimetro.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Helmholtz)

    def retranslateUi(self, Helmholtz):
        Helmholtz.setWindowTitle(_translate("Helmholtz", "Bobina de Helmholtz", None))
        self.tabWidget.setStatusTip(_translate("Helmholtz", "Software de Controle da Bobina de Helmholtz", None))
        self.label_10.setText(_translate("Helmholtz", "Comunicação", None))
        self.label.setText(_translate("Helmholtz", "Porta Display :", None))
        self.cb_PortaDisplay.setStatusTip(_translate("Helmholtz", "Porta de Comunicação Serial do Display Heidenhain", None))
        self.cb_PortaDisplay.setItemText(0, _translate("Helmholtz", "Com1", None))
        self.cb_PortaDisplay.setItemText(1, _translate("Helmholtz", "Com2", None))
        self.cb_PortaDisplay.setItemText(2, _translate("Helmholtz", "Com3", None))
        self.cb_PortaDisplay.setItemText(3, _translate("Helmholtz", "Com4", None))
        self.cb_PortaDisplay.setItemText(4, _translate("Helmholtz", "Com5", None))
        self.cb_PortaDisplay.setItemText(5, _translate("Helmholtz", "Com6", None))
        self.cb_PortaDisplay.setItemText(6, _translate("Helmholtz", "Com7", None))
        self.cb_PortaDisplay.setItemText(7, _translate("Helmholtz", "Com8", None))
        self.cb_PortaDisplay.setItemText(8, _translate("Helmholtz", "Com9", None))
        self.cb_PortaDisplay.setItemText(9, _translate("Helmholtz", "Com10", None))
        self.cb_PortaDisplay.setItemText(10, _translate("Helmholtz", "Com11", None))
        self.cb_PortaDisplay.setItemText(11, _translate("Helmholtz", "Com12", None))
        self.cb_PortaDisplay.setItemText(12, _translate("Helmholtz", "Com13", None))
        self.cb_PortaDisplay.setItemText(13, _translate("Helmholtz", "Com14", None))
        self.cb_PortaDisplay.setItemText(14, _translate("Helmholtz", "Com15", None))
        self.label_2.setText(_translate("Helmholtz", "Porta Driver :", None))
        self.cb_PortaDriver.setStatusTip(_translate("Helmholtz", "Porta de Comunicação Serial do Driver Parker", None))
        self.cb_PortaDriver.setItemText(0, _translate("Helmholtz", "Com1", None))
        self.cb_PortaDriver.setItemText(1, _translate("Helmholtz", "Com2", None))
        self.cb_PortaDriver.setItemText(2, _translate("Helmholtz", "Com3", None))
        self.cb_PortaDriver.setItemText(3, _translate("Helmholtz", "Com4", None))
        self.cb_PortaDriver.setItemText(4, _translate("Helmholtz", "Com5", None))
        self.cb_PortaDriver.setItemText(5, _translate("Helmholtz", "Com6", None))
        self.cb_PortaDriver.setItemText(6, _translate("Helmholtz", "Com7", None))
        self.cb_PortaDriver.setItemText(7, _translate("Helmholtz", "Com8", None))
        self.cb_PortaDriver.setItemText(8, _translate("Helmholtz", "Com9", None))
        self.cb_PortaDriver.setItemText(9, _translate("Helmholtz", "Com10", None))
        self.cb_PortaDriver.setItemText(10, _translate("Helmholtz", "Com11", None))
        self.cb_PortaDriver.setItemText(11, _translate("Helmholtz", "Com12", None))
        self.cb_PortaDriver.setItemText(12, _translate("Helmholtz", "Com13", None))
        self.cb_PortaDriver.setItemText(13, _translate("Helmholtz", "Com14", None))
        self.cb_PortaDriver.setItemText(14, _translate("Helmholtz", "Com15", None))
        self.label_3.setText(_translate("Helmholtz", "Porta Integrador :", None))
        self.le_EndIntegrador.setStatusTip(_translate("Helmholtz", "Endereço da Porta GPIB do Integrador", None))
        self.le_EndIntegrador.setText(_translate("Helmholtz", "28", None))
        self.pb_ConectarDispositivos.setStatusTip(_translate("Helmholtz", "Conecta Dispositivos", None))
        self.pb_ConectarDispositivos.setText(_translate("Helmholtz", "Conectar Dispositivos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Helmholtz", "Bobina de Helmholtz", None))
        self.pb_temperatura.setStatusTip(_translate("Helmholtz", "Conecta Dispositivos", None))
        self.pb_temperatura.setText(_translate("Helmholtz", "Conectar", None))
        self.cb_PortaMultimetro.setStatusTip(_translate("Helmholtz", "Porta de Comunicação Serial do Display Heidenhain", None))
        self.cb_PortaMultimetro.setItemText(0, _translate("Helmholtz", "Com1", None))
        self.cb_PortaMultimetro.setItemText(1, _translate("Helmholtz", "Com2", None))
        self.cb_PortaMultimetro.setItemText(2, _translate("Helmholtz", "Com3", None))
        self.cb_PortaMultimetro.setItemText(3, _translate("Helmholtz", "Com4", None))
        self.cb_PortaMultimetro.setItemText(4, _translate("Helmholtz", "Com5", None))
        self.cb_PortaMultimetro.setItemText(5, _translate("Helmholtz", "Com6", None))
        self.cb_PortaMultimetro.setItemText(6, _translate("Helmholtz", "Com7", None))
        self.cb_PortaMultimetro.setItemText(7, _translate("Helmholtz", "Com8", None))
        self.cb_PortaMultimetro.setItemText(8, _translate("Helmholtz", "Com9", None))
        self.cb_PortaMultimetro.setItemText(9, _translate("Helmholtz", "Com10", None))
        self.cb_PortaMultimetro.setItemText(10, _translate("Helmholtz", "Com11", None))
        self.cb_PortaMultimetro.setItemText(11, _translate("Helmholtz", "Com12", None))
        self.cb_PortaMultimetro.setItemText(12, _translate("Helmholtz", "Com13", None))
        self.cb_PortaMultimetro.setItemText(13, _translate("Helmholtz", "Com14", None))
        self.cb_PortaMultimetro.setItemText(14, _translate("Helmholtz", "Com15", None))
        self.label_47.setText(_translate("Helmholtz", "Nº de Medidas: ", None))
        self.label_49.setText(_translate("Helmholtz", "Atual:    ", None))
        self.label_atual.setText(_translate("Helmholtz", "0        ", None))
        self.le_error.setText(_translate("Helmholtz", "OK", None))
        self.pb_IniciaColeta.setStatusTip(_translate("Helmholtz", "Conecta Dispositivos", None))
        self.pb_IniciaColeta.setText(_translate("Helmholtz", "Iniciar", None))
        self.pb_PararColeta.setStatusTip(_translate("Helmholtz", "Conecta Dispositivos", None))
        self.pb_PararColeta.setText(_translate("Helmholtz", "Parar", None))
        self.cb_Salvar.setText(_translate("Helmholtz", "Salvar", None))
        self.cb_ArmazenaTempo.setText(_translate("Helmholtz", "Armazenar Tempo", None))
        self.label_48.setText(_translate("Helmholtz", "Intervalo: ", None))
        self.le_Intervalo.setText(_translate("Helmholtz", "1", None))
        self.label_50.setText(_translate("Helmholtz", " Segundos          ", None))
        self.label_43.setText(_translate("Helmholtz", "Tempo de Espera (ms): ", None))
        self.le_espera.setText(_translate("Helmholtz", "360", None))
        self.label_46.setText(_translate("Helmholtz", "Resistência Cabo (ohms): ", None))
        self.le_resistencia.setText(_translate("Helmholtz", "0.8202", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Helmholtz", "Temperatura", None))
        self.pb_SalvarParametros.setText(_translate("Helmholtz", "Checar valores e salvar alterações", None))
        self.label_4.setText(_translate("Helmholtz", "Endereço Driver :", None))
        self.label_5.setText(_translate("Helmholtz", "Velocidade de Medida :", None))
        self.label_6.setText(_translate("Helmholtz", "Aceleração de Medida :", None))
        self.label_7.setText(_translate("Helmholtz", "# Voltas Medida :", None))
        self.label_8.setText(_translate("Helmholtz", "Pulsos Encoder :", None))
        self.label_9.setText(_translate("Helmholtz", "Passos Motor :", None))
        self.le_PassosMotor.setText(_translate("Helmholtz", "50000", None))
        self.label_12.setText(_translate("Helmholtz", "# Pontos Integração :", None))
        self.cb_PontosIntegracao.setItemText(0, _translate("Helmholtz", "4", None))
        self.cb_PontosIntegracao.setItemText(1, _translate("Helmholtz", "8", None))
        self.cb_PontosIntegracao.setItemText(2, _translate("Helmholtz", "16", None))
        self.cb_PontosIntegracao.setItemText(3, _translate("Helmholtz", "32", None))
        self.cb_PontosIntegracao.setItemText(4, _translate("Helmholtz", "64", None))
        self.cb_PontosIntegracao.setItemText(5, _translate("Helmholtz", "128", None))
        self.cb_PontosIntegracao.setItemText(6, _translate("Helmholtz", "256", None))
        self.cb_PontosIntegracao.setItemText(7, _translate("Helmholtz", "512", None))
        self.label_13.setText(_translate("Helmholtz", "Pulsos para Trigger :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Helmholtz", "Parâmetros", None))
        self.label_14.setText(_translate("Helmholtz", "Parâmetros Bobinas", None))
        self.label_15.setText(_translate("Helmholtz", "# Espiras :", None))
        self.label_16.setText(_translate("Helmholtz", "Raio 1 :", None))
        self.label_17.setText(_translate("Helmholtz", "Raio 2 :", None))
        self.label_18.setText(_translate("Helmholtz", "Dist Centro :", None))
        self.pb_SalvarBobina.setText(_translate("Helmholtz", "Checar valores e salvar alterações", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Helmholtz", "Bobina", None))
        self.label_19.setText(_translate("Helmholtz", "Movimentação dos Motores", None))
        self.label_20.setText(_translate("Helmholtz", "Velocidade :", None))
        self.label_21.setText(_translate("Helmholtz", "Aceleração :", None))
        self.label_22.setText(_translate("Helmholtz", "Número de Voltas :", None))
        self.cb_HabilitaEncoder.setText(_translate("Helmholtz", "Habilita Leitura Encoder :", None))
        self.pb_MoverMotor.setText(_translate("Helmholtz", "Mover Motor", None))
        self.pb_PararMotor.setText(_translate("Helmholtz", "Parar Motor", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Helmholtz", "Motores", None))
        self.label_26.setText(_translate("Helmholtz", "Medida de Offset da Helmholtz", None))
        self.pb_ZerarOffsets.setText(_translate("Helmholtz", "Zerar Offsets", None))
        item = self.tw_GanhosOffsets.horizontalHeaderItem(0)
        item.setText(_translate("Helmholtz", "Ganhos", None))
        item = self.tw_GanhosOffsets.horizontalHeaderItem(1)
        item.setText(_translate("Helmholtz", "Offsets", None))
        __sortingEnabled = self.tw_GanhosOffsets.isSortingEnabled()
        self.tw_GanhosOffsets.setSortingEnabled(False)
        item = self.tw_GanhosOffsets.item(0, 0)
        item.setText(_translate("Helmholtz", "1", None))
        item = self.tw_GanhosOffsets.item(1, 0)
        item.setText(_translate("Helmholtz", "2", None))
        item = self.tw_GanhosOffsets.item(2, 0)
        item.setText(_translate("Helmholtz", "5", None))
        item = self.tw_GanhosOffsets.item(3, 0)
        item.setText(_translate("Helmholtz", "10", None))
        item = self.tw_GanhosOffsets.item(4, 0)
        item.setText(_translate("Helmholtz", "20", None))
        item = self.tw_GanhosOffsets.item(5, 0)
        item.setText(_translate("Helmholtz", "50", None))
        item = self.tw_GanhosOffsets.item(6, 0)
        item.setText(_translate("Helmholtz", "100", None))
        self.tw_GanhosOffsets.setSortingEnabled(__sortingEnabled)
        self.label_24.setText(_translate("Helmholtz", "# Voltas Medida :", None))
        self.label_25.setText(_translate("Helmholtz", "Ganho Integrador :", None))
        self.cb_GanhoOffset.setItemText(0, _translate("Helmholtz", "1", None))
        self.cb_GanhoOffset.setItemText(1, _translate("Helmholtz", "2", None))
        self.cb_GanhoOffset.setItemText(2, _translate("Helmholtz", "5", None))
        self.cb_GanhoOffset.setItemText(3, _translate("Helmholtz", "10", None))
        self.cb_GanhoOffset.setItemText(4, _translate("Helmholtz", "20", None))
        self.cb_GanhoOffset.setItemText(5, _translate("Helmholtz", "50", None))
        self.cb_GanhoOffset.setItemText(6, _translate("Helmholtz", "100", None))
        self.pb_AjusteOffset.setText(_translate("Helmholtz", "Ajustar Offset Integrador", None))
        self.pb_PararMedOffset.setText(_translate("Helmholtz", "Parar", None))
        self.pb_IniciarMedOffset.setText(_translate("Helmholtz", "Iniciar Medição", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Helmholtz", "Medir Offsets", None))
        self.label_28.setText(_translate("Helmholtz", "Dimensões do Bloco :", None))
        self.rb_DimensaoManual.setText(_translate("Helmholtz", "Manual", None))
        self.rb_DimensaoAuto.setText(_translate("Helmholtz", "Automática", None))
        self.label_27.setText(_translate("Helmholtz", "Volume do Bloco :", None))
        self.le_VolumeBloco.setStatusTip(_translate("Helmholtz", "Quando em modo MANUAL, pressione ENTER para salvar as alterações.", None))
        self.label_44.setText(_translate("Helmholtz", "m³", None))
        self.cb_SubtrairVolume.setText(_translate("Helmholtz", "Subtrair Volume :", None))
        self.le_VolumeSubtracao.setStatusTip(_translate("Helmholtz", "Quando em modo MANUAL, pressione ENTER para salvar as alterações.", None))
        self.label_45.setText(_translate("Helmholtz", "m³", None))
        self.cb_CompPriMz.setText(_translate("Helmholtz", "Componente Principal", None))
        self.label_29.setText(_translate("Helmholtz", "Ganho :", None))
        self.cb_GanhoOffset_Mz.setItemText(0, _translate("Helmholtz", "1", None))
        self.cb_GanhoOffset_Mz.setItemText(1, _translate("Helmholtz", "2", None))
        self.cb_GanhoOffset_Mz.setItemText(2, _translate("Helmholtz", "5", None))
        self.cb_GanhoOffset_Mz.setItemText(3, _translate("Helmholtz", "10", None))
        self.cb_GanhoOffset_Mz.setItemText(4, _translate("Helmholtz", "20", None))
        self.cb_GanhoOffset_Mz.setItemText(5, _translate("Helmholtz", "50", None))
        self.cb_GanhoOffset_Mz.setItemText(6, _translate("Helmholtz", "100", None))
        self.cb_CompSecMx.setText(_translate("Helmholtz", "Componente Secundária", None))
        self.cb_CompSecMy.setText(_translate("Helmholtz", "Componente Secundária", None))
        self.label_30.setText(_translate("Helmholtz", "Ganho :", None))
        self.label_31.setText(_translate("Helmholtz", "Ganho :", None))
        self.cb_GanhoOffset_Mx.setItemText(0, _translate("Helmholtz", "1", None))
        self.cb_GanhoOffset_Mx.setItemText(1, _translate("Helmholtz", "2", None))
        self.cb_GanhoOffset_Mx.setItemText(2, _translate("Helmholtz", "5", None))
        self.cb_GanhoOffset_Mx.setItemText(3, _translate("Helmholtz", "10", None))
        self.cb_GanhoOffset_Mx.setItemText(4, _translate("Helmholtz", "20", None))
        self.cb_GanhoOffset_Mx.setItemText(5, _translate("Helmholtz", "50", None))
        self.cb_GanhoOffset_Mx.setItemText(6, _translate("Helmholtz", "100", None))
        self.cb_GanhoOffset_My.setItemText(0, _translate("Helmholtz", "1", None))
        self.cb_GanhoOffset_My.setItemText(1, _translate("Helmholtz", "2", None))
        self.cb_GanhoOffset_My.setItemText(2, _translate("Helmholtz", "5", None))
        self.cb_GanhoOffset_My.setItemText(3, _translate("Helmholtz", "10", None))
        self.cb_GanhoOffset_My.setItemText(4, _translate("Helmholtz", "20", None))
        self.cb_GanhoOffset_My.setItemText(5, _translate("Helmholtz", "50", None))
        self.cb_GanhoOffset_My.setItemText(6, _translate("Helmholtz", "100", None))
        self.label_32.setText(_translate("Helmholtz", "Mz", None))
        self.label_33.setText(_translate("Helmholtz", "Mx", None))
        self.label_34.setText(_translate("Helmholtz", "My", None))
        self.pb_IniciarMedicao.setText(_translate("Helmholtz", "Iniciar Medição", None))
        self.pb_PararMedicao.setText(_translate("Helmholtz", "Parar", None))
        self.cb_SalvarDadosGerais.setText(_translate("Helmholtz", "Salvar Resultados no Arquivo Geral de Resumos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Helmholtz", "Medir Componentes", None))
        self.label_35.setText(_translate("Helmholtz", "Média Mz :", None))
        self.label_36.setText(_translate("Helmholtz", "Desvio Mz :", None))
        self.label_37.setText(_translate("Helmholtz", "Média Mx :", None))
        self.label_38.setText(_translate("Helmholtz", "Desvio Mx :", None))
        self.label_39.setText(_translate("Helmholtz", "Média My :", None))
        self.label_40.setText(_translate("Helmholtz", "Desvio My :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Helmholtz", "Resultados", None))

from PlotGUI2y import matplotlibWidget_2
from PlotGUI import matplotlibWidget
