# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_Helmholtz.ui'
#
# Created: Tue Jul 29 11:10:46 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Helmholtz(object):
    def setupUi(self, Helmholtz):
        Helmholtz.setObjectName(_fromUtf8("Helmholtz"))
        Helmholtz.resize(756, 368)
        Helmholtz.setWindowTitle(QtGui.QApplication.translate("Helmholtz", "Bobina de Helmholtz", None, QtGui.QApplication.UnicodeUTF8))
        Helmholtz.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.centralwidget = QtGui.QWidget(Helmholtz)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 758, 328))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStatusTip(QtGui.QApplication.translate("Helmholtz", "Software de Controle da Bobina de Helmholtz", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(460, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setText(QtGui.QApplication.translate("Helmholtz", "Comunicação", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_42 = QtGui.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(50, 0, 301, 291))
        self.label_42.setText(_fromUtf8(""))
        self.label_42.setPixmap(QtGui.QPixmap(_fromUtf8("Imagens/Helmholtz2.jpg")))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.layoutWidget = QtGui.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(401, 81, 305, 111))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(67)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("Helmholtz", "Porta Display :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cb_PortaDisplay = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_PortaDisplay.setFont(font)
        self.cb_PortaDisplay.setStatusTip(QtGui.QApplication.translate("Helmholtz", "Porta de Comunicação Serial do Display Heidenhain", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.setObjectName(_fromUtf8("cb_PortaDisplay"))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(0, QtGui.QApplication.translate("Helmholtz", "Com1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(1, QtGui.QApplication.translate("Helmholtz", "Com2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(2, QtGui.QApplication.translate("Helmholtz", "Com3", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(3, QtGui.QApplication.translate("Helmholtz", "Com4", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(4, QtGui.QApplication.translate("Helmholtz", "Com5", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(5, QtGui.QApplication.translate("Helmholtz", "Com6", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(6, QtGui.QApplication.translate("Helmholtz", "Com7", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(7, QtGui.QApplication.translate("Helmholtz", "Com8", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(8, QtGui.QApplication.translate("Helmholtz", "Com9", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(9, QtGui.QApplication.translate("Helmholtz", "Com10", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(10, QtGui.QApplication.translate("Helmholtz", "Com11", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(11, QtGui.QApplication.translate("Helmholtz", "Com12", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(12, QtGui.QApplication.translate("Helmholtz", "Com13", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(13, QtGui.QApplication.translate("Helmholtz", "Com14", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDisplay.addItem(_fromUtf8(""))
        self.cb_PortaDisplay.setItemText(14, QtGui.QApplication.translate("Helmholtz", "Com15", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.cb_PortaDisplay, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("Helmholtz", "Porta Driver :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.cb_PortaDriver = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_PortaDriver.setFont(font)
        self.cb_PortaDriver.setStatusTip(QtGui.QApplication.translate("Helmholtz", "Porta de Comunicação Serial do Driver Parker", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.setObjectName(_fromUtf8("cb_PortaDriver"))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(0, QtGui.QApplication.translate("Helmholtz", "Com1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(1, QtGui.QApplication.translate("Helmholtz", "Com2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(2, QtGui.QApplication.translate("Helmholtz", "Com3", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(3, QtGui.QApplication.translate("Helmholtz", "Com4", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(4, QtGui.QApplication.translate("Helmholtz", "Com5", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(5, QtGui.QApplication.translate("Helmholtz", "Com6", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(6, QtGui.QApplication.translate("Helmholtz", "Com7", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(7, QtGui.QApplication.translate("Helmholtz", "Com8", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(8, QtGui.QApplication.translate("Helmholtz", "Com9", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(9, QtGui.QApplication.translate("Helmholtz", "Com10", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(10, QtGui.QApplication.translate("Helmholtz", "Com11", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(11, QtGui.QApplication.translate("Helmholtz", "Com12", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(12, QtGui.QApplication.translate("Helmholtz", "Com13", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(13, QtGui.QApplication.translate("Helmholtz", "Com14", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PortaDriver.addItem(_fromUtf8(""))
        self.cb_PortaDriver.setItemText(14, QtGui.QApplication.translate("Helmholtz", "Com15", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.cb_PortaDriver, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Helmholtz", "Porta Integrador :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.le_EndIntegrador = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_EndIntegrador.setFont(font)
        self.le_EndIntegrador.setStatusTip(QtGui.QApplication.translate("Helmholtz", "Endereço da Porta GPIB do Integrador", None, QtGui.QApplication.UnicodeUTF8))
        self.le_EndIntegrador.setText(QtGui.QApplication.translate("Helmholtz", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.le_EndIntegrador.setObjectName(_fromUtf8("le_EndIntegrador"))
        self.gridLayout.addWidget(self.le_EndIntegrador, 2, 1, 1, 1)
        self.pb_ConectarDispositivos = QtGui.QPushButton(self.tab_3)
        self.pb_ConectarDispositivos.setGeometry(QtCore.QRect(401, 207, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_ConectarDispositivos.setFont(font)
        self.pb_ConectarDispositivos.setStatusTip(QtGui.QApplication.translate("Helmholtz", "Conecta Dispositivos", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ConectarDispositivos.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pb_ConectarDispositivos.setText(QtGui.QApplication.translate("Helmholtz", "Conectar Dispositivos", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ConectarDispositivos.setIcon(icon)
        self.pb_ConectarDispositivos.setIconSize(QtCore.QSize(35, 35))
        self.pb_ConectarDispositivos.setObjectName(_fromUtf8("pb_ConectarDispositivos"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.pb_SalvarParametros = QtGui.QPushButton(self.tab_5)
        self.pb_SalvarParametros.setGeometry(QtCore.QRect(195, 224, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_SalvarParametros.setFont(font)
        self.pb_SalvarParametros.setText(QtGui.QApplication.translate("Helmholtz", "Checar valores e salvar alterações", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621493_Burn Disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_SalvarParametros.setIcon(icon1)
        self.pb_SalvarParametros.setIconSize(QtCore.QSize(35, 35))
        self.pb_SalvarParametros.setObjectName(_fromUtf8("pb_SalvarParametros"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(90, 30, 561, 171))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("Helmholtz", "Endereço Driver :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.le_EndDriver = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_EndDriver.setObjectName(_fromUtf8("le_EndDriver"))
        self.gridLayout_2.addWidget(self.le_EndDriver, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText(QtGui.QApplication.translate("Helmholtz", "Velocidade de Medida :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.le_VelMedida = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_VelMedida.setText(_fromUtf8(""))
        self.le_VelMedida.setObjectName(_fromUtf8("le_VelMedida"))
        self.gridLayout_2.addWidget(self.le_VelMedida, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("Helmholtz", "Aceleração de Medida :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.le_AceMedida = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_AceMedida.setObjectName(_fromUtf8("le_AceMedida"))
        self.gridLayout_2.addWidget(self.le_AceMedida, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("Helmholtz", "# Voltas Medida :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.le_NVoltas = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_NVoltas.setObjectName(_fromUtf8("le_NVoltas"))
        self.gridLayout_2.addWidget(self.le_NVoltas, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setText(QtGui.QApplication.translate("Helmholtz", "Pulsos Encoder :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.le_PulsosEncoder = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_PulsosEncoder.setObjectName(_fromUtf8("le_PulsosEncoder"))
        self.gridLayout_3.addWidget(self.le_PulsosEncoder, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setText(QtGui.QApplication.translate("Helmholtz", "Passos Motor :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.le_PassosMotor = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_PassosMotor.setObjectName(_fromUtf8("le_PassosMotor"))
        self.gridLayout_3.addWidget(self.le_PassosMotor, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setText(QtGui.QApplication.translate("Helmholtz", "# Pontos Integração :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.cb_PontosIntegracao = QtGui.QComboBox(self.layoutWidget_2)
        self.cb_PontosIntegracao.setObjectName(_fromUtf8("cb_PontosIntegracao"))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.setItemText(0, QtGui.QApplication.translate("Helmholtz", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.setItemText(1, QtGui.QApplication.translate("Helmholtz", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.setItemText(2, QtGui.QApplication.translate("Helmholtz", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.setItemText(3, QtGui.QApplication.translate("Helmholtz", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.setItemText(4, QtGui.QApplication.translate("Helmholtz", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.setItemText(5, QtGui.QApplication.translate("Helmholtz", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.setItemText(6, QtGui.QApplication.translate("Helmholtz", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PontosIntegracao.addItem(_fromUtf8(""))
        self.cb_PontosIntegracao.setItemText(7, QtGui.QApplication.translate("Helmholtz", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_3.addWidget(self.cb_PontosIntegracao, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setText(QtGui.QApplication.translate("Helmholtz", "Pulsos para Trigger :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.le_TriggerAlinhamento = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_TriggerAlinhamento.setObjectName(_fromUtf8("le_TriggerAlinhamento"))
        self.gridLayout_3.addWidget(self.le_TriggerAlinhamento, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(110, 32, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setText(QtGui.QApplication.translate("Helmholtz", "Parâmetros Bobinas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 80, 360, 180))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setSpacing(14)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setContentsMargins(10, 1, 0, -1)
        self.gridLayout_4.setHorizontalSpacing(45)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_15 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setText(QtGui.QApplication.translate("Helmholtz", "# Espiras :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.le_nEspiras = QtGui.QLineEdit(self.layoutWidget_3)
        self.le_nEspiras.setObjectName(_fromUtf8("le_nEspiras"))
        self.gridLayout_4.addWidget(self.le_nEspiras, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setText(QtGui.QApplication.translate("Helmholtz", "Raio 1 :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.le_Raio1 = QtGui.QLineEdit(self.layoutWidget_3)
        self.le_Raio1.setObjectName(_fromUtf8("le_Raio1"))
        self.gridLayout_4.addWidget(self.le_Raio1, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setText(QtGui.QApplication.translate("Helmholtz", "Raio 2 :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.le_Raio2 = QtGui.QLineEdit(self.layoutWidget_3)
        self.le_Raio2.setObjectName(_fromUtf8("le_Raio2"))
        self.gridLayout_4.addWidget(self.le_Raio2, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setText(QtGui.QApplication.translate("Helmholtz", "Dist Centro :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 3, 0, 1, 1)
        self.le_DistCentro = QtGui.QLineEdit(self.layoutWidget_3)
        self.le_DistCentro.setObjectName(_fromUtf8("le_DistCentro"))
        self.gridLayout_4.addWidget(self.le_DistCentro, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.pb_SalvarBobina = QtGui.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_SalvarBobina.setFont(font)
        self.pb_SalvarBobina.setText(QtGui.QApplication.translate("Helmholtz", "Checar valores e salvar alterações", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621516_Burn Disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_SalvarBobina.setIcon(icon2)
        self.pb_SalvarBobina.setIconSize(QtCore.QSize(35, 35))
        self.pb_SalvarBobina.setObjectName(_fromUtf8("pb_SalvarBobina"))
        self.verticalLayout_3.addWidget(self.pb_SalvarBobina)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(430, 10, 301, 291))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8("Imagens/HelmholtzConfig.png")))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(80, 30, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setText(QtGui.QApplication.translate("Helmholtz", "Movimentação dos Motores", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(450, 40, 231, 221))
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setPixmap(QtGui.QPixmap(_fromUtf8("Imagens/MotorPasso4.png")))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.layoutWidget_4 = QtGui.QWidget(self.tab_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(70, 80, 301, 141))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_20 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setText(QtGui.QApplication.translate("Helmholtz", "Velocidade :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_12.addWidget(self.label_20, 0, 0, 1, 1)
        self.le_VelMotor = QtGui.QLineEdit(self.layoutWidget_4)
        self.le_VelMotor.setObjectName(_fromUtf8("le_VelMotor"))
        self.gridLayout_12.addWidget(self.le_VelMotor, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setText(QtGui.QApplication.translate("Helmholtz", "Aceleração :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_12.addWidget(self.label_21, 1, 0, 1, 1)
        self.le_AceMotor = QtGui.QLineEdit(self.layoutWidget_4)
        self.le_AceMotor.setObjectName(_fromUtf8("le_AceMotor"))
        self.gridLayout_12.addWidget(self.le_AceMotor, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setText(QtGui.QApplication.translate("Helmholtz", "Número de Voltas :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_12.addWidget(self.label_22, 2, 0, 1, 1)
        self.cb_HabilitaEncoder = QtGui.QCheckBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_HabilitaEncoder.setFont(font)
        self.cb_HabilitaEncoder.setText(QtGui.QApplication.translate("Helmholtz", "Habilita Leitura Encoder :", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_HabilitaEncoder.setObjectName(_fromUtf8("cb_HabilitaEncoder"))
        self.gridLayout_12.addWidget(self.cb_HabilitaEncoder, 3, 0, 1, 1)
        self.le_NVoltasMotor = QtGui.QLineEdit(self.layoutWidget_4)
        self.le_NVoltasMotor.setObjectName(_fromUtf8("le_NVoltasMotor"))
        self.gridLayout_12.addWidget(self.le_NVoltasMotor, 2, 1, 1, 1)
        self.le_LeituraEncoder = QtGui.QLineEdit(self.layoutWidget_4)
        self.le_LeituraEncoder.setReadOnly(True)
        self.le_LeituraEncoder.setObjectName(_fromUtf8("le_LeituraEncoder"))
        self.gridLayout_12.addWidget(self.le_LeituraEncoder, 3, 1, 1, 1)
        self.pb_MoverMotor = QtGui.QPushButton(self.tab_4)
        self.pb_MoverMotor.setGeometry(QtCore.QRect(70, 234, 145, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_MoverMotor.setFont(font)
        self.pb_MoverMotor.setText(QtGui.QApplication.translate("Helmholtz", "Mover Motor", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621501_Check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_MoverMotor.setIcon(icon3)
        self.pb_MoverMotor.setObjectName(_fromUtf8("pb_MoverMotor"))
        self.pb_PararMotor = QtGui.QPushButton(self.tab_4)
        self.pb_PararMotor.setEnabled(False)
        self.pb_PararMotor.setGeometry(QtCore.QRect(230, 234, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_PararMotor.setFont(font)
        self.pb_PararMotor.setText(QtGui.QApplication.translate("Helmholtz", "Parar Motor", None, QtGui.QApplication.UnicodeUTF8))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621507_Delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_PararMotor.setIcon(icon4)
        self.pb_PararMotor.setObjectName(_fromUtf8("pb_PararMotor"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_26 = QtGui.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(60, 20, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setText(QtGui.QApplication.translate("Helmholtz", "Medida de Offset da Helmholtz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.pb_ZerarOffsets = QtGui.QPushButton(self.tab)
        self.pb_ZerarOffsets.setGeometry(QtCore.QRect(480, 260, 161, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_ZerarOffsets.setFont(font)
        self.pb_ZerarOffsets.setText(QtGui.QApplication.translate("Helmholtz", "Zerar Offsets", None, QtGui.QApplication.UnicodeUTF8))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/botao_limpar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ZerarOffsets.setIcon(icon5)
        self.pb_ZerarOffsets.setIconSize(QtCore.QSize(30, 30))
        self.pb_ZerarOffsets.setObjectName(_fromUtf8("pb_ZerarOffsets"))
        self.tw_GanhosOffsets = QtGui.QTableWidget(self.tab)
        self.tw_GanhosOffsets.setGeometry(QtCore.QRect(430, 14, 260, 245))
        self.tw_GanhosOffsets.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tw_GanhosOffsets.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tw_GanhosOffsets.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tw_GanhosOffsets.setSelectionBehavior(QtGui.QAbstractItemView.SelectColumns)
        self.tw_GanhosOffsets.setRowCount(7)
        self.tw_GanhosOffsets.setObjectName(_fromUtf8("tw_GanhosOffsets"))
        self.tw_GanhosOffsets.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Helmholtz", "Ganhos", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_GanhosOffsets.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Helmholtz", "Offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_GanhosOffsets.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Helmholtz", "1", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Helmholtz", "2", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Helmholtz", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_GanhosOffsets.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Helmholtz", "10", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Helmholtz", "20", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Helmholtz", "50", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Helmholtz", "100", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tw_GanhosOffsets.setItem(6, 1, item)
        self.tw_GanhosOffsets.horizontalHeader().setStretchLastSection(True)
        self.tw_GanhosOffsets.verticalHeader().setVisible(False)
        self.layoutWidget_5 = QtGui.QWidget(self.tab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(74, 63, 271, 151))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setVerticalSpacing(24)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_24 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setText(QtGui.QApplication.translate("Helmholtz", "# Voltas Medida :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_6.addWidget(self.label_24, 0, 0, 1, 1)
        self.le_NVoltasOffset = QtGui.QLineEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_NVoltasOffset.setFont(font)
        self.le_NVoltasOffset.setObjectName(_fromUtf8("le_NVoltasOffset"))
        self.gridLayout_6.addWidget(self.le_NVoltasOffset, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setText(QtGui.QApplication.translate("Helmholtz", "Ganho Integrador :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_6.addWidget(self.label_25, 1, 0, 1, 1)
        self.cb_GanhoOffset = QtGui.QComboBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_GanhoOffset.setFont(font)
        self.cb_GanhoOffset.setObjectName(_fromUtf8("cb_GanhoOffset"))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.setItemText(0, QtGui.QApplication.translate("Helmholtz", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.setItemText(1, QtGui.QApplication.translate("Helmholtz", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.setItemText(2, QtGui.QApplication.translate("Helmholtz", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.setItemText(3, QtGui.QApplication.translate("Helmholtz", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.setItemText(4, QtGui.QApplication.translate("Helmholtz", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.setItemText(5, QtGui.QApplication.translate("Helmholtz", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset.addItem(_fromUtf8(""))
        self.cb_GanhoOffset.setItemText(6, QtGui.QApplication.translate("Helmholtz", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_6.addWidget(self.cb_GanhoOffset, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.pb_AjusteOffset = QtGui.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_AjusteOffset.setFont(font)
        self.pb_AjusteOffset.setText(QtGui.QApplication.translate("Helmholtz", "Ajustar Offset Integrador", None, QtGui.QApplication.UnicodeUTF8))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/FerramentaAjuste.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_AjusteOffset.setIcon(icon6)
        self.pb_AjusteOffset.setIconSize(QtCore.QSize(50, 50))
        self.pb_AjusteOffset.setObjectName(_fromUtf8("pb_AjusteOffset"))
        self.verticalLayout_4.addWidget(self.pb_AjusteOffset)
        self.pb_PararMedOffset = QtGui.QPushButton(self.tab)
        self.pb_PararMedOffset.setEnabled(False)
        self.pb_PararMedOffset.setGeometry(QtCore.QRect(211, 235, 156, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_PararMedOffset.setFont(font)
        self.pb_PararMedOffset.setText(QtGui.QApplication.translate("Helmholtz", "Parar", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_PararMedOffset.setIcon(icon4)
        self.pb_PararMedOffset.setObjectName(_fromUtf8("pb_PararMedOffset"))
        self.pb_IniciarMedOffset = QtGui.QPushButton(self.tab)
        self.pb_IniciarMedOffset.setGeometry(QtCore.QRect(48, 235, 157, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_IniciarMedOffset.setFont(font)
        self.pb_IniciarMedOffset.setText(QtGui.QApplication.translate("Helmholtz", "Iniciar Medição", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_IniciarMedOffset.setIcon(icon3)
        self.pb_IniciarMedOffset.setObjectName(_fromUtf8("pb_IniciarMedOffset"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gb_MedirComponentes = QtGui.QGroupBox(self.tab_6)
        self.gb_MedirComponentes.setGeometry(QtCore.QRect(30, 10, 361, 281))
        self.gb_MedirComponentes.setTitle(_fromUtf8(""))
        self.gb_MedirComponentes.setObjectName(_fromUtf8("gb_MedirComponentes"))
        self.pb_Medicao = QtGui.QProgressBar(self.gb_MedirComponentes)
        self.pb_Medicao.setGeometry(QtCore.QRect(10, 245, 341, 23))
        self.pb_Medicao.setProperty("value", 50)
        self.pb_Medicao.setAlignment(QtCore.Qt.AlignCenter)
        self.pb_Medicao.setTextVisible(True)
        self.pb_Medicao.setOrientation(QtCore.Qt.Horizontal)
        self.pb_Medicao.setInvertedAppearance(False)
        self.pb_Medicao.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.pb_Medicao.setObjectName(_fromUtf8("pb_Medicao"))
        self.layoutWidget_6 = QtGui.QWidget(self.gb_MedirComponentes)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 13, 341, 101))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_28 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setText(QtGui.QApplication.translate("Helmholtz", "Dimensões do Bloco :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_7.addWidget(self.label_28, 1, 0, 1, 1)
        self.rb_DimensaoManual = QtGui.QRadioButton(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_DimensaoManual.setFont(font)
        self.rb_DimensaoManual.setText(QtGui.QApplication.translate("Helmholtz", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_DimensaoManual.setCheckable(True)
        self.rb_DimensaoManual.setChecked(False)
        self.rb_DimensaoManual.setObjectName(_fromUtf8("rb_DimensaoManual"))
        self.gridLayout_7.addWidget(self.rb_DimensaoManual, 1, 1, 1, 1)
        self.rb_DimensaoAuto = QtGui.QRadioButton(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_DimensaoAuto.setFont(font)
        self.rb_DimensaoAuto.setText(QtGui.QApplication.translate("Helmholtz", "Automática", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_DimensaoAuto.setObjectName(_fromUtf8("rb_DimensaoAuto"))
        self.gridLayout_7.addWidget(self.rb_DimensaoAuto, 1, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setText(QtGui.QApplication.translate("Helmholtz", "Volume do Bloco :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_7.addWidget(self.label_27, 2, 0, 1, 1)
        self.le_VolumeBloco = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco.setFont(font)
        self.le_VolumeBloco.setStatusTip(QtGui.QApplication.translate("Helmholtz", "Quando em modo MANUAL, pressione ENTER para salvar as alterações.", None, QtGui.QApplication.UnicodeUTF8))
        self.le_VolumeBloco.setReadOnly(True)
        self.le_VolumeBloco.setObjectName(_fromUtf8("le_VolumeBloco"))
        self.gridLayout_7.addWidget(self.le_VolumeBloco, 2, 1, 1, 2)
        self.label_44 = QtGui.QLabel(self.layoutWidget_6)
        self.label_44.setText(QtGui.QApplication.translate("Helmholtz", "m³", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_7.addWidget(self.label_44, 2, 3, 1, 1)
        self.cb_SubtrairVolume = QtGui.QCheckBox(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_SubtrairVolume.setFont(font)
        self.cb_SubtrairVolume.setText(QtGui.QApplication.translate("Helmholtz", "Subtrair Volume :", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_SubtrairVolume.setObjectName(_fromUtf8("cb_SubtrairVolume"))
        self.gridLayout_7.addWidget(self.cb_SubtrairVolume, 3, 0, 1, 1)
        self.le_VolumeSubtracao = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeSubtracao.setFont(font)
        self.le_VolumeSubtracao.setStatusTip(QtGui.QApplication.translate("Helmholtz", "Quando em modo MANUAL, pressione ENTER para salvar as alterações.", None, QtGui.QApplication.UnicodeUTF8))
        self.le_VolumeSubtracao.setReadOnly(True)
        self.le_VolumeSubtracao.setObjectName(_fromUtf8("le_VolumeSubtracao"))
        self.gridLayout_7.addWidget(self.le_VolumeSubtracao, 3, 1, 1, 2)
        self.label_45 = QtGui.QLabel(self.layoutWidget_6)
        self.label_45.setText(QtGui.QApplication.translate("Helmholtz", "m³", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_7.addWidget(self.label_45, 3, 3, 1, 1)
        self.layoutWidget_7 = QtGui.QWidget(self.gb_MedirComponentes)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 129, 341, 111))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_7)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cb_CompPriMz = QtGui.QCheckBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_CompPriMz.setFont(font)
        self.cb_CompPriMz.setText(QtGui.QApplication.translate("Helmholtz", "Componente Principal", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_CompPriMz.setObjectName(_fromUtf8("cb_CompPriMz"))
        self.gridLayout_8.addWidget(self.cb_CompPriMz, 0, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setText(QtGui.QApplication.translate("Helmholtz", "Ganho :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_8.addWidget(self.label_29, 0, 2, 1, 1)
        self.cb_GanhoOffset_Mz = QtGui.QComboBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_GanhoOffset_Mz.setFont(font)
        self.cb_GanhoOffset_Mz.setObjectName(_fromUtf8("cb_GanhoOffset_Mz"))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.setItemText(0, QtGui.QApplication.translate("Helmholtz", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.setItemText(1, QtGui.QApplication.translate("Helmholtz", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.setItemText(2, QtGui.QApplication.translate("Helmholtz", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.setItemText(3, QtGui.QApplication.translate("Helmholtz", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.setItemText(4, QtGui.QApplication.translate("Helmholtz", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.setItemText(5, QtGui.QApplication.translate("Helmholtz", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mz.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mz.setItemText(6, QtGui.QApplication.translate("Helmholtz", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_8.addWidget(self.cb_GanhoOffset_Mz, 0, 3, 1, 1)
        self.cb_CompSecMx = QtGui.QCheckBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_CompSecMx.setFont(font)
        self.cb_CompSecMx.setText(QtGui.QApplication.translate("Helmholtz", "Componente Secundária", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_CompSecMx.setObjectName(_fromUtf8("cb_CompSecMx"))
        self.gridLayout_8.addWidget(self.cb_CompSecMx, 1, 0, 1, 1)
        self.cb_CompSecMy = QtGui.QCheckBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_CompSecMy.setFont(font)
        self.cb_CompSecMy.setText(QtGui.QApplication.translate("Helmholtz", "Componente Secundária", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_CompSecMy.setObjectName(_fromUtf8("cb_CompSecMy"))
        self.gridLayout_8.addWidget(self.cb_CompSecMy, 2, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setText(QtGui.QApplication.translate("Helmholtz", "Ganho :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_8.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setText(QtGui.QApplication.translate("Helmholtz", "Ganho :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_8.addWidget(self.label_31, 2, 2, 1, 1)
        self.cb_GanhoOffset_Mx = QtGui.QComboBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_GanhoOffset_Mx.setFont(font)
        self.cb_GanhoOffset_Mx.setObjectName(_fromUtf8("cb_GanhoOffset_Mx"))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.setItemText(0, QtGui.QApplication.translate("Helmholtz", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.setItemText(1, QtGui.QApplication.translate("Helmholtz", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.setItemText(2, QtGui.QApplication.translate("Helmholtz", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.setItemText(3, QtGui.QApplication.translate("Helmholtz", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.setItemText(4, QtGui.QApplication.translate("Helmholtz", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.setItemText(5, QtGui.QApplication.translate("Helmholtz", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_Mx.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_Mx.setItemText(6, QtGui.QApplication.translate("Helmholtz", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_8.addWidget(self.cb_GanhoOffset_Mx, 1, 3, 1, 1)
        self.cb_GanhoOffset_My = QtGui.QComboBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_GanhoOffset_My.setFont(font)
        self.cb_GanhoOffset_My.setObjectName(_fromUtf8("cb_GanhoOffset_My"))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.setItemText(0, QtGui.QApplication.translate("Helmholtz", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.setItemText(1, QtGui.QApplication.translate("Helmholtz", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.setItemText(2, QtGui.QApplication.translate("Helmholtz", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.setItemText(3, QtGui.QApplication.translate("Helmholtz", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.setItemText(4, QtGui.QApplication.translate("Helmholtz", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.setItemText(5, QtGui.QApplication.translate("Helmholtz", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_GanhoOffset_My.addItem(_fromUtf8(""))
        self.cb_GanhoOffset_My.setItemText(6, QtGui.QApplication.translate("Helmholtz", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_8.addWidget(self.cb_GanhoOffset_My, 2, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setText(QtGui.QApplication.translate("Helmholtz", "Mz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_8.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setText(QtGui.QApplication.translate("Helmholtz", "Mx", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_8.addWidget(self.label_33, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setText(QtGui.QApplication.translate("Helmholtz", "My", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_8.addWidget(self.label_34, 2, 1, 1, 1)
        self.pb_IniciarMedicao = QtGui.QPushButton(self.tab_6)
        self.pb_IniciarMedicao.setGeometry(QtCore.QRect(430, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_IniciarMedicao.setFont(font)
        self.pb_IniciarMedicao.setText(QtGui.QApplication.translate("Helmholtz", "Iniciar Medição", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_IniciarMedicao.setIcon(icon3)
        self.pb_IniciarMedicao.setObjectName(_fromUtf8("pb_IniciarMedicao"))
        self.pb_PararMedicao = QtGui.QPushButton(self.tab_6)
        self.pb_PararMedicao.setEnabled(False)
        self.pb_PararMedicao.setGeometry(QtCore.QRect(602, 200, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_PararMedicao.setFont(font)
        self.pb_PararMedicao.setText(QtGui.QApplication.translate("Helmholtz", "Parar", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_PararMedicao.setIcon(icon4)
        self.pb_PararMedicao.setObjectName(_fromUtf8("pb_PararMedicao"))
        self.cb_SalvarDadosGerais = QtGui.QCheckBox(self.tab_6)
        self.cb_SalvarDadosGerais.setGeometry(QtCore.QRect(410, 260, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_SalvarDadosGerais.setFont(font)
        self.cb_SalvarDadosGerais.setText(QtGui.QApplication.translate("Helmholtz", "Salvar Resultados no Arquivo Geral de Resumos", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_SalvarDadosGerais.setObjectName(_fromUtf8("cb_SalvarDadosGerais"))
        self.label_41 = QtGui.QLabel(self.tab_6)
        self.label_41.setGeometry(QtCore.QRect(460, 20, 221, 191))
        self.label_41.setText(_fromUtf8(""))
        self.label_41.setPixmap(QtGui.QPixmap(_fromUtf8("Imagens/Helmholtz_vs2.jpg")))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_2.setGeometry(QtCore.QRect(0, -1, 751, 72))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setText(QtGui.QApplication.translate("Helmholtz", "Média Mz :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_9.addWidget(self.label_35, 0, 0, 1, 1)
        self.le_VolumeBloco_3 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_3.setFont(font)
        self.le_VolumeBloco_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.le_VolumeBloco_3.setText(_fromUtf8(""))
        self.le_VolumeBloco_3.setReadOnly(True)
        self.le_VolumeBloco_3.setObjectName(_fromUtf8("le_VolumeBloco_3"))
        self.gridLayout_9.addWidget(self.le_VolumeBloco_3, 0, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setText(QtGui.QApplication.translate("Helmholtz", "Desvio Mz :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_9.addWidget(self.label_36, 1, 0, 1, 1)
        self.le_VolumeBloco_4 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_4.setFont(font)
        self.le_VolumeBloco_4.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.le_VolumeBloco_4.setText(_fromUtf8(""))
        self.le_VolumeBloco_4.setReadOnly(True)
        self.le_VolumeBloco_4.setObjectName(_fromUtf8("le_VolumeBloco_4"))
        self.gridLayout_9.addWidget(self.le_VolumeBloco_4, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_9)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setText(QtGui.QApplication.translate("Helmholtz", "Média Mx :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_10.addWidget(self.label_37, 0, 0, 1, 1)
        self.le_VolumeBloco_5 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_5.setFont(font)
        self.le_VolumeBloco_5.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.le_VolumeBloco_5.setText(_fromUtf8(""))
        self.le_VolumeBloco_5.setReadOnly(True)
        self.le_VolumeBloco_5.setObjectName(_fromUtf8("le_VolumeBloco_5"))
        self.gridLayout_10.addWidget(self.le_VolumeBloco_5, 0, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setText(QtGui.QApplication.translate("Helmholtz", "Desvio Mx :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_10.addWidget(self.label_38, 1, 0, 1, 1)
        self.le_VolumeBloco_6 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_6.setFont(font)
        self.le_VolumeBloco_6.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.le_VolumeBloco_6.setText(_fromUtf8(""))
        self.le_VolumeBloco_6.setReadOnly(True)
        self.le_VolumeBloco_6.setObjectName(_fromUtf8("le_VolumeBloco_6"))
        self.gridLayout_10.addWidget(self.le_VolumeBloco_6, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_10)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setText(QtGui.QApplication.translate("Helmholtz", "Média My :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_11.addWidget(self.label_39, 0, 0, 1, 1)
        self.le_VolumeBloco_7 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_7.setFont(font)
        self.le_VolumeBloco_7.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.le_VolumeBloco_7.setText(_fromUtf8(""))
        self.le_VolumeBloco_7.setReadOnly(True)
        self.le_VolumeBloco_7.setObjectName(_fromUtf8("le_VolumeBloco_7"))
        self.gridLayout_11.addWidget(self.le_VolumeBloco_7, 0, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setText(QtGui.QApplication.translate("Helmholtz", "Desvio My :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_11.addWidget(self.label_40, 1, 0, 1, 1)
        self.le_VolumeBloco_8 = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_VolumeBloco_8.setFont(font)
        self.le_VolumeBloco_8.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.le_VolumeBloco_8.setText(_fromUtf8(""))
        self.le_VolumeBloco_8.setReadOnly(True)
        self.le_VolumeBloco_8.setObjectName(_fromUtf8("le_VolumeBloco_8"))
        self.gridLayout_11.addWidget(self.le_VolumeBloco_8, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_11)
        self.widget = matplotlibWidget(self.tab_7)
        self.widget.setGeometry(QtCore.QRect(0, 65, 376, 230))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.widget_2 = matplotlibWidget_2(self.tab_7)
        self.widget_2.setGeometry(QtCore.QRect(380, 65, 376, 230))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        Helmholtz.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Helmholtz)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Helmholtz.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Helmholtz)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Helmholtz.setStatusBar(self.statusbar)

        self.retranslateUi(Helmholtz)
        self.tabWidget.setCurrentIndex(0)
        self.cb_PortaDisplay.setCurrentIndex(3)
        self.cb_PortaDriver.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Helmholtz)

    def retranslateUi(self, Helmholtz):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Helmholtz", "Bobina de Helmholtz", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Helmholtz", "Parâmetros", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Helmholtz", "Bobina", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Helmholtz", "Motores", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tw_GanhosOffsets.horizontalHeaderItem(0)
        item = self.tw_GanhosOffsets.horizontalHeaderItem(1)
        __sortingEnabled = self.tw_GanhosOffsets.isSortingEnabled()
        self.tw_GanhosOffsets.setSortingEnabled(False)
        item = self.tw_GanhosOffsets.item(0, 0)
        item = self.tw_GanhosOffsets.item(1, 0)
        item = self.tw_GanhosOffsets.item(2, 0)
        item = self.tw_GanhosOffsets.item(3, 0)
        item = self.tw_GanhosOffsets.item(4, 0)
        item = self.tw_GanhosOffsets.item(5, 0)
        item = self.tw_GanhosOffsets.item(6, 0)
        self.tw_GanhosOffsets.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Helmholtz", "Medir Offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("Helmholtz", "Medir Componentes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("Helmholtz", "Resultados", None, QtGui.QApplication.UnicodeUTF8))

from PlotGUI2y import matplotlibWidget_2
from PlotGUI import matplotlibWidget
